local v = vim.opt
v.background = "dark"
v.clipboard = "unnamedplus"
v.cursorline = true
v.hidden = true
v.mouse = "a"
v.number = true
v.wildmenu = true
v.syntax = "on"
v.completeopt = "noinsert,menuone,noselect"
v.termguicolors = true
v.shiftwidth = 2
v.tabstop = 2
v.expandtab = true
v.wrap = false
v.so = 5
v.siso = 4
v.filetype = "on"
--v.guifont = "10"
--v.filetype = "indent,on"
--v.smartindent = true
v.splitbelow = true
v.splitright = true
v.list = false
v.listchars = { tab = "▸ ", trail = "·" }
v.relativenumber = true
vim.g.mapleader = ";"
v.laststatus = 3
vim.o.laststatus = 3
-- v.foldmethod = "expr"
-- v.foldexpr = "nvim_treesitter#foldexpr()"
